ARG ELK_VERSION
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

ARG PIPELINE_LOCATION

COPY ./logstash/pipeline/${PIPELINE_LOCATION}/*.conf /usr/share/logstash/pipeline/
COPY ./logstash/pipeline/${PIPELINE_LOCATION}/*.rb /home/logstash/scripts/