# Workflow triggered when an issue is opened
name: Issue opened

on:
  issues:
    types: [opened]

jobs:
  start-prepare-release:
    if: github.event.issue.title == 'Prepare CLI Release'
    permissions:
      # required for pushing release branch
      contents: write
      # require for commenting on issue
      issues: write
    uses: ./.github/workflows/prepare-cli-release.yml
