name: Release Cli

on:
  push:
    tags:
      - "cli/v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Extract tag
        id: extract_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "The value of TAG_NAME it $TAG_NAME"
          echo "The value of GITHUB_REF_NAME is $GITHUB_REF_NAME"
      # - name: Get project.version
      #   # We get the current project.version
      #   run: |
      #     VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      #     echo "project.version from pom: $VERSION"
      #     echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Test
        run: mvn test -f cli/demo/pom.xml
      - name: Build
        run: mvn clean package -f cli/demo/pom.xml
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            cli/demo/target/demo*.jar