name: Release Cli

on:
  push:
    tags:
      - "cli/v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: mvn test -f cli/demo/pom.xml
      - name: Build
        run: mvn clean package -f cli/demo/pom.xml
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            cli/demo/target/demo*.jar